const DELETE_AREAS = "DELETE_AREAS";
const ADD_AREA = "ADD_AREA";
const UPDATE_IN_DRAG_AREAS = "UPDATE_IN_DRAG_AREAS";
const UPDATE_AREAS = "UPDATE_AREAS";
const ASSIGN_AREA_INDEX = "ASSIGN_AREA_INDEX";
const UPDATE_AREA = "UPDATE_AREA";
const SELECT_AREAS = "SELECT_AREAS";

export {
    DELETE_AREAS,
    ADD_AREA,
    UPDATE_IN_DRAG_AREAS,
    UPDATE_AREAS,
    ASSIGN_AREA_INDEX,
    UPDATE_AREA,
    SELECT_AREAS,
};