const DELETE_SLIDES = "DELETE_SLIDES";
const ADD_SLIDE = "ADD_SLIDE";
const MOVE_SLIDES = "MOVE_SLIDES";
const ASSIGN_SLIDE_INDEX = "ASSIGN_SLIDE_INDEX";
const SELECT_SLIDES = "SELECT_SLIDES";
const UPDATE_SLIDE_PROPERTY = "UPDATE_SLIDE_PROPERTY"; 

export {
    DELETE_SLIDES,
    ADD_SLIDE,
    MOVE_SLIDES,
    ASSIGN_SLIDE_INDEX,
    SELECT_SLIDES,
    UPDATE_SLIDE_PROPERTY,
};